ARG VERSION=latest
FROM csprock/python-data-science:${VERSION}

LABEL author="Carson Sprock <csprock@gmail.com>"

USER user

COPY ./scripts/requirements-ts.txt requirements.txt
RUN pip install --user -r requirements.txt && rm requirements.txt