ARG TAG=python-base-latest
FROM csprock/dockerfiles:${TAG}

LABEL author="Carson Sprock <csprock@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive

USER user

COPY ./scripts/requirements-data-science.txt requirements.txt
RUN pip install --user -r requirements.txt && rm requirements.txt