ARG TAG=python-data-science-latest
FROM csprock/dockerfiles:${TAG}

LABEL author="Carson Sprock <csprock@gmail.com>"

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    gfortran \
    file \
    patch \
    pkg-config \
    zlib1g-dev \
    bison \
    flex \
    libgmp-dev \
    libreadline-dev \
    libncurses5-dev \
    glpk-utils \
    libblas-dev \
    libopenblas-dev \
    liblapack-dev \
    coinor-cbc \
    coinor-libcbc-dev \
    libmetis-dev \
    libgfortran-11-dev


# install ASL
RUN git clone https://github.com/coin-or-tools/ThirdParty-ASL.git \
    && cd ThirdParty-ASL \
    && ./get.ASL \
    && ./configure \
    && make \
    && make install

# install MUMPS
RUN git clone https://github.com/coin-or-tools/ThirdParty-Mumps.git \
    && cd ThirdParty-Mumps \
    && ./get.Mumps \
    && ./configure \
    && make \
    && make install

# install IPOPT
RUN git clone --branch stable/3.14 https://github.com/coin-or/Ipopt.git \
    && cd Ipopt \
    && mkdir build \
    && cd build \
    && ../configure \
    && make \
    && make test \
    && make install \
    && ldconfig

# install Bonmin
RUN git clone --branch releases/1.8.8 https://github.com/coin-or/Bonmin.git \
    && cd Bonmin \
    && mkdir build \
    && cd build \
    && ../configure -C --prefix=/usr \
    && make \
    && make test \
    && make install \
    && ldconfig

USER user
COPY ./scripts/requirements-opt.txt requirements.txt
RUN pip install -r requirements.txt && rm requirements.txt
