version: '3.8'
services:
  lambda:
    build:
      context: .
      dockerfile: ./Dockerfile-lambda
    container_name: test_lambda
    ports:
      - "9002:8080"
    environment:
      AWS_LAMBDA_FUNCTION_NAME: test-lambda
      AWS_LAMBDA_FUNCTION_TIMEOUT: 30
      AWS_LAMBDA_FUNCTION_MEMORY_SIZE: 512
    command: ["handler.handler"]
    working_dir: /app